### PR TITLE
Optimize logo image

### PR DESCRIPTION
**Pull request by RDIL**
Quality same but file smaller.  The app I'm using sometimes does mess up though just going to put that out there.

### CODE REVIEW

**Comment by RDIL** [comment]
oh shit i cant get the bot to sign :/

**Comment by kerbybit** [comment]
Make sure you open the CLA in the same tab, don't middle click. I made that mistake a while ago

**Comment by FalseHonesty** [comment]
@kerbybit smh, he signed it, but the bot is the one that actually made the commit so the bot has to sign it

**Comment by RDIL** [comment]
It’s an application I can’t sign into it

**Comment by RDIL** [comment]
Hey uh @FalseHonesty is there a chance you could take a look at my 14 PRs:
https://github.com/HyperiumClient/Hyperium/pulls

**Pull request closed without merging**
