### PR TITLE
BlockPos: Add getAllInBox method

### PR DESCRIPTION
**Pull request by Marvinschs**
This provides an alternative to the method of using nested for loops for x, y, z and the calls to `World.getBlockAt(x, y, z)` just to get Blocks in a certain area.

### CODE REVIEW

**Comment by mattco98** [comment]
Why `BlockPos` instead of `Block`? Also this should probably be `World.getBlocksInCube` or something

**Comment by Marvinschs** [comment]
`BlockPos` because it is the same in mc.

**Comment by mattco98** [comment]
Well I guess I was referencing the PR description:

> This provides an alternative to the method of using nested for loops for x, y, z and the calls to World.getBlockAt(x, y, z) just to get Blocks in a certain area.

The above doesn't really seem true, since `getBlockAt` returns a `Block`, not a `BlockPos`

**Comment by Marvinschs** [comment]
You are right `getBlockAt` returns a `Block` but before one had to use constructs like this:
```js
for (let x = 0; x < radius * 2; x++) {
      for (let z = 0; z < radius * 2; z++) {
        for (let y = 0; y < radius * 2; y++) {
          let pos = new BlockPos(cachedX - radius + x, cashedY - radius + y, cachedZ - radius + z)
          var block = World.getBlockAt(pos)
          //...
```

**Pull request closed without merging**
