### PR TITLE
Add getEntity to the Entity wrapper

### PR DESCRIPTION
**Pull request by WalshyDev**
This is so that I can access net.minecraft Entity specific methods.

### CODE REVIEW

**Comment by FalseHonesty** [comment]
Just add a `@Getter` to the entity field :)

**Comment by WalshyDev** [comment]
Yeah I was thinking that looking through other classes.

**Comment by WalshyDev** [comment]
By the way I can't sign the CLA currently, seems to be some issues. It seemingly kept expiring the token on approval and trying to then make me re-authorize. Now GitHub has flagged it as suspicious abuse.
https://bots.are-pretty.sexy/20ba84.png

**Comment by FalseHonesty** [comment]
Thank you for your contribution! <3

**Pull request merged**
