### PR TITLE
Color dependency modules in gray

### PR DESCRIPTION
**Pull request by ixnoahlive**
Added a key that colours modules gray in the module list if the isLibrary metadata key is set to true.

### CODE REVIEW

**Comment by mattco98** [comment]
Why would we not use the already present `isRequired` value?

**Comment by ixnoahlive** [comment]
@mattco98 I was not informed this was for libraries, and thought it was for general dependencies and mods packaged together. I'll gladly edit this PR to fix the problem.

**Comment by mattco98** [comment]
`isRequired` is true when the module is depended on by another, which is pretty much the definition of a library. 

Also, please do not close issues until they are actually resolved (i.e. until the PR is closed)

**Comment by ixnoahlive** [comment]
Pull req. updated to fix this, sorry for all the trouble.

**Comment by mattco98** [comment]
Please squash your commits. Also, do not submit code without testing it, or at the _very_ least compiling it. As it is, this code will not compile.

**Comment by ixnoahlive** [comment]
Hm, was very certain this was functional. Looking into it. I am quite busy at the minute but I'll do my best to resolve these gripes.

**Pull request closed without merging**
