### PR TITLE
Promote https

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Comment by mattco98** [comment]
This actually breaks tinypic. If you open the contributing in your repo, you can see that all of the https tinypic urls don't load. What you could do is upload all the images to imgur and then replace all of the links with those urls.

**Comment by RDIL** [comment]
oof ok

**Comment by FalseHonesty** [comment]
@RDIL yeah

**Comment by kerbybit** [comment]
We should probably just upload these images directly to the ct website

**Comment by RDIL** [comment]
I’ll put it on imgur later for ya guys

**Pull request closed without merging**
