### PR TITLE
shut up nobody cares

### PR DESCRIPTION
**Pull request by GamingGeek**

### CODE REVIEW

**Review by lyndseyy — APPROVED** [review]
This Looks Good To Me

**Comment by MisterCheezeCake** [comment]
Seems good but why is this necessary?

**Comment by FalseHonesty** [comment]
This logging is kinda nice sometimes tho :(

**Comment by DJtheRedstoner** [comment]
> This logging is kinda nice sometimes tho :(

Except f+ is dead, the entire check should be removed, if you do want some logging make it something like `Successfully registered ASM transformers`

**Review by builder-247 — APPROVED** [review]

**Comment by glasss13** [comment]
Resolved in https://github.com/ChatTriggers/ChatTriggers/commit/4171f8f5fac81ff687ab328ee062ffc705fa43b0

**Pull request closed without merging**
