### PR TITLE
Added player armor getters

### PR DESCRIPTION
**Pull request by qkleinfelter**

### CODE REVIEW

**Comment by mattco98** [comment]
Inside each function, you have to ensure that `mc.thePlayer` is not null. Otherwise, the game will instantly crash as soon as it starts (because `mc.thePlayer` is null while in the main menu). See the other functions in that file as examples.

**Comment by qkleinfelter** [comment]
ok this should work now @FalseHonesty

**Comment by qkleinfelter** [comment]
also in my last commit i changed the armor getters to return the display name instead of the toString

**Comment by qkleinfelter** [comment]
@FalseHonesty @kerbybit

**Comment by qkleinfelter** [comment]
Closing cause matt basically rewrote my stuff but betterer

**Pull request closed without merging**
